### ISSUE TITLE
Icon Gray

### ISSUE THREAD

**Issue by mendelmintz** [hamada2029/gphotos_sort#1]
Hey, everything seams to almost work, aside from the Icon and GPhotos sort option are gray. When are you able to click on them? 
![picture1](https://user-images.githubusercontent.com/43712280/46251589-cd7a2100-c424-11e8-87ec-f04ddb091734.png)

**Comment by hamada2029** [comment]
Top of context menu is Chrome Web Store link.
It has been not available.
Because I did not register GPhotos extension for the store.

Icon's color will be black(available) at Google Photos album URL.
(https://photos.google.com/album/XXXXXXXX)
Just album. Not other Google Photos URLs.
