### ISSUE TITLE
Infinite loop Sorting...

### ISSUE THREAD

**Issue by thegreengree** [hamada2029/gphotos_sort#13]
So it worked fine 2 days ago, but now when I click a button it just hangs on "Sorting..." loop.
I specifically reinstalled the plugin, rebooted PC, and created a small test album with just a few photos.
Looking forward to an update about that

**Comment by hamada2029** [comment]
Thank you for reports.
Please check v0.17.

**Comment by thegreengree** [comment]
Yep, everything is working now. Thank you a lot for a quick fix and the extension in general! 👍 
Its really stupid that this is not a default functionality :|
