### ISSUE TITLE
Can't load the extension

### ISSUE THREAD

**Issue by slgwv** [hamada2029/gphotos_sort#22]
When I try to load the extension I get an error in the manifest.json file:  "Line 7 Column 1 Unexpected token".

And figuring out what's wrong is _way_ above my pay grade ;)

Thanks!

**Comment by hamada2029** [comment]
manifest.json file got something wrong.
Could you try to re-download?

**Comment by slgwv** [comment]
It's still giving the same error.  The system is tripping over that very first line: <!DOCTYPE html>
Running manifest.json thru the online JSON validator gives:

Error: Parse error on line 1:
<!DOCTYPE html >	<
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

So, dunno what's happening...

**Comment by slgwv** [comment]
Thanks for checking, but I'm still getting the same error.  I've put
details in a comment on your site.

**Comment by hamada2029** [comment]
Maybe you validated wrong file.
Because "<" is not in manifest.json.
Please try this link.
https://github.com/hamada2029/gphotos_sort/archive/refs/tags/v0.25.zip
