### ISSUE TITLE
Not working again..

### ISSUE THREAD

**Issue by mendelmintz** [hamada2029/gphotos_sort#4]

**Comment by hamada2029** [comment]
Umm, I can sort on my currently test.
Please post popup console.
(RIght click on extension popup window. And select 'inspect'.)

**Comment by rbalister** [comment]
Unable to right click on extension popup as the menu shows "GPhotos Sort" greyed out and not selectable.  From the extension menu, clicking on "Inspect Popup" doesn't do anything.  I'm running google chrome version 74.0.3729.169 64-bit

![image](https://user-images.githubusercontent.com/51107066/58451571-f5b83d80-80e1-11e9-94b5-5675917016f2.png)

**Comment by hamada2029** [comment]
Don't popup when accessing your album direct URL?
(ex: https://photos.google.com/album/XXXXXXXX)

**Comment by rbalister** [comment]
Ah, now I see.  I have several albums in my google photos account.  From the album page, hovering over some of the albums I see the URL as https://photos.google.com/album/xxxxxxxx and others show up as https://photos.google.com/share/xxxxxxxx.  The one that I was trying to sort and it didn't work was one of the share ones.  When I specifically looked for one that had album in the link, it did work.  I do need to create some test files and see if it works and reorders according to file name.  Now that I know why it didn't work before, and what to do to make it work now, I can go further.  Possibly this difference between share and album is something that can be added in the future.  Thanks for the work on this.

**Comment by rbalister** [comment]
After further experimenting, it would seem that any album you create uses the photos.google.com/album/xxxxx format.  Once you share it in any way, it is moved to the photos.google.com/share/xxxxx format.

**Comment by rbalister** [comment]
I was able to see results on a small test group of five files.  I moved on to a larger selection containing 220 files.  This is a group that google seems to think they know better on how to order.  When I went to sort them I get the following.  First one of these pop up dialogs:

![image](https://user-images.githubusercontent.com/51107066/58515181-0f08ca80-8172-11e9-9d2b-44aac317e279.png)

Followed by 30-40 of these popups.

![image](https://user-images.githubusercontent.com/51107066/58515163-fd272780-8171-11e9-963d-15257cd48b4d.png)

I did open the inspect popup prior to attempting to sort.  Once the script was done running I saved the console log to the attached file.

[holhfpnjghnmifhmngaomhcibbdegmnn-1559080171632.log](https://github.com/hamada2029/gphotos_sort/files/3229842/holhfpnjghnmifhmngaomhcibbdegmnn-1559080171632.log)

In the end, it didn't seem as if anything got sorted on this larger test case.

**Comment by mendelmintz** [comment]
Yes, same happened by me.

Although few months ago, it did work, now though this keeps on popping up.

**Comment by mendelmintz** [comment]
<img width="960" alt="B090AA98-54B4-4DBD-A349-22BF8A86BB03" src="https://user-images.githubusercontent.com/43712280/58520669-ce677c00-8186-11e9-9b4b-10094b039e82.png">

**Comment by hamada2029** [comment]
One access is necessary for one file name.
There are limit now on many accesses. (100?)

Share album sort looks like different method.

**Comment by mendelmintz** [comment]
Is there a way to fix and allow more pictures?

I am trying to sort 200 photos, and the same error comes up

**Comment by hamada2029** [comment]
Added setTimeout. (About 5files/sec)
Running time will be little slower.
I could sort 189 files.

**Comment by mendelmintz** [comment]
Perfect, works!

**Comment by rbalister** [comment]
I too can confirm that this does work on larger albums.

I see that there is some distinction in the diffs for the share type albums.  Is there going to be anything developed that allows the sort on those or is the API too different for those album types?

どうも  :)

**Comment by hamada2029** [comment]
Official photo API is bit too complicated for just file sorting extension.
(Certification, Quota, etc.)
I will try to check share album sorting on next rest time.

**Comment by hamada2029** [comment]
I can be sorting share albums now.
Please test new commit.

**Comment by rbalister** [comment]
Hamada-san,
Thanks!  That fixed it.  Your extension will now sort both the private "album" albums and the shared "share" albums.  Works great.  Thank you for your efforts on this.  This now will enable me to continue to use Google Photos as ordering was not working right the way Google implemented it.

**Comment by mendelmintz** [comment]
Thank you as well, this means a lot to our business as we publish Google photos albums all the time.

I do have another question, although not related to this extension. Is there a way you'd be able to create a tool to embed the Google Photos album into an HTML code, so I could embed it into my site. I'd pay if you can develop such a code.

Thanks

**Comment by hamada2029** [comment]
It's hard to embed whole function of Google Photos.
But simpler HTML, for example image cards? tiles?
I think I can generate such codes from public album.

**Comment by mendelmintz** [comment]
Perfect. Looking forward.

All our albums are public at RebbeDrive.com/photos

I'd want to embed them to our site instead of just linking.
