### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by dangleweed** [hamada2029/gphotos_sort#5]
Is there a way to list the files in numeric order rather than text order? For example, currently files are listed like:
11.jpg
110.jpg
5.jpg
88.jpg

Can the sort order be changed to list numerically to this:
5.jpg
11.jpg
88.jpg
110.jpg

Thanks!

**Comment by hamada2029** [comment]
Added numerical order.

**Comment by dangleweed** [comment]
Awesome. thank you!
