### ISSUE TITLE
Not all photos in large albums are sorted

### ISSUE THREAD

**Issue by nadavhames** [hamada2029/gphotos_sort#6]
For albums with greater than 550 pictures, only the first 550 get sorted. Is this a rest limitation? For my album of ~2500 pictures, 543 pictures get sorted.

**Comment by hamada2029** [comment]
Changed to new sort method.
And I could sort 508 photos album. 
(Limitation was 500.)
Please test greater album.

**Comment by nadavhames** [comment]
It now works with my big album. Everything has been sorted. Much better, thank you!
