### ISSUE TITLE
Doesn't work at expected

### ISSUE THREAD

**Issue by RobiGold1** [hamada2029/gphotos_sort#7]
When I click the button I get what you can see in link below instead of what you write in the guide.[https://photos.google.com/u/1/album/AF1QipORavhgXFDeMVx1X-cUwIbnRBCiUK7iNcEKw5cB/photo/AF1QipNDovDppGIrIkuLyUBCjYqQZwQpTSVFyDOidMdx](url)

Used to work a couple of months ago.

Please help ASAP as without this extension it's very difficult to manage a large number of photos in the album

**Comment by hamada2029** [comment]
I can not access your album URL.
And, my current test is succeed without any errors.
Please try newest version.
https://github.com/hamada2029/gphotos_sort/releases

**Comment by RobiGold1** [comment]
Hello,

Thanks for your quick reply

Could not load from your link:

Failed to load extension
File~\Downloads\gphotos_sort-0.1
ErrorManifest file is missing or unreadable
Could not load manifest.

Also see attached image of what happens when I click on the extension from GitHub

BR,

Robi

**Comment by hamada2029** [comment]
You have to check that manifest.json file exists in expanded folder.
If do not exist, you should use proper expand app.

**Comment by RobiGold1** [comment]
Succeeded to load now, but still same problem: clicking on extension produces attached menu (first) instead of second attachment.

**Comment by hamada2029** [comment]
I couldn't get what you mean.
But if you have been installing old and new, you have to uninstall older one.

**Comment by RobiGold1** [comment]
I have removed the old extension before installing the new one.
Have you looked at the attachment ? (I attach again and insert it in the mail also)

[cid:image001.jpg@01D55CB1.1634BF20]

**Comment by hamada2029** [comment]
You should response on github if you want to attach image.

**Comment by RobiGold1** [comment]
![Boxer_1566803242 028929_asset](https://user-images.githubusercontent.com/17319603/63749500-3deb2580-c8b4-11e9-8793-66b896cc9769.JPG)

Attached !!!

**Comment by hamada2029** [comment]
I think you logged in on your browser by multiple users.
If you log out all users and log in by single user, maybe you can use this extension for now.

I think I can fix for multiple users later.

**Comment by RobiGold1** [comment]
Thanks, but I don’t think that’s the problem – it’s my computer and only I log in. This a work computer and my hunch is that our IT department has done something that prevent users from working with extensions.

I’ll try on a private computer and let you know if it interests you

**Comment by hamada2029** [comment]
Your album URL (https://photos.google.com/u/1/...) is multiple users.
If you logged in by single, your URL must be ...com/u/0/album/... or ...com/album/... .

Whichever, I fixed for /u/X/.

**Comment by RobiGold1** [comment]
Thanks, you were right, that was the problem. Works OK now !!!! 🙏
