### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by dangleweed** [hamada2029/gphotos_sort#8]
Not used this tool for a while, but tried today. I keep getting this error:
Is this no longer working?

Thanks

![image](https://user-images.githubusercontent.com/33907587/72171699-6c811d00-33cb-11ea-9526-ef9c6675e3a2.png)

**Comment by hamada2029** [comment]
I did a little fix.
Please test it.

**Comment by dangleweed** [comment]
Hey,
Looks like it's fixed :-)

Many thanks!
