### ISSUE TITLE
Seeing Issue #8 on MacOS 10.13.6 & Chrome 79.0.3945.117 with Version 0.11

### ISSUE THREAD

**Issue by etcetra** [hamada2029/gphotos_sort#9]
I am getting the same error as addressed in Issue #8.

https://github.com/hamada2029/gphotos_sort/issues/8

After pressing the Sort by Name button I see this:

![Screen Shot 2020-01-14 at 7 24 13 AM](https://user-images.githubusercontent.com/57885738/72348022-0cc29480-369f-11ea-834e-3906f99f9b5f.png)

The icon at the top continues to spin and the progress bar remains frozen.

The following error is shown:

![Screen Shot 2020-01-14 at 7 29 15 AM](https://user-images.githubusercontent.com/57885738/72348248-9e320680-369f-11ea-8030-e96391c8558c.png)

Version 0.11
Chrome Version 79.0.3945.117 (Official Build) (64-bit)
MacOS High Sierra 10.13.6

**Comment by hamada2029** [comment]
I think you used older version.
Please check newest one.

**Comment by etcetra** [comment]
Hello,

I've downloaded both versions and get the same error.

**Comment by hamada2029** [comment]
Is it really same error?

```const script_p = /<script nonce=[^<]+key: 'ds:1'[^<]+<\/script>/;```
This line was slightly changed at new version.

**Comment by etcetra** [comment]
I open the js file from both versions in TextWrangler and created a screen shot.

I do not see a difference in the lines.

![Screen Shot 2020-01-15 at 7 25 56 PM](https://user-images.githubusercontent.com/57885738/72485372-2b26ae00-37cd-11ea-94c5-40ed8131335f.png)

**Comment by hamada2029** [comment]
Very sorry.
I forgot update releases.
https://github.com/hamada2029/gphotos_sort/releases
Please check new release.

**Comment by etcetra** [comment]
I am glad the screenshot was helpful.

**Thank you so much!**

It works great. I tried it on several different folders.

Have you thought about joining the GitHub Sponsors program?

There are many Google Photos users that have been requesting this feature from Google Photos for years but have been ignored by Google. I think some of these users would make a donation to you for all the time this extension saves verses manually cutom sorting images. I'd make a donation :0)

**EXCELLENT WORK!**

**Comment by hamada2029** [comment]
Thanks.
I will consider GitHub Sponsors.
